const ORDER_STATUS = {
  CREATED: "CREATED",
  ACCEPTED_BY_ADMIN: "ACCEPTED_BY_ADMIN",
  ASSIGNED_TO_DELIVERY: "ASSIGNED_TO_DELIVERY",
  PICKED_UP: "PICKED_UP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  ARRIVED_AT_LOCATION: "ARRIVED_AT_LOCATION",
  OTP_VERIFIED: "OTP_VERIFIED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
};

module.exports = { ORDER_STATUS, ROLES };
