const mongoose = require("mongoose");

const orderSchema = new mongoose.Schema({
  orderId: {
    type: String,
    unique: true,
    // Not required - will be auto-generated by pre-save hook
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  deliveryAddress: {
    addressId: mongoose.Schema.Types.ObjectId,
    addressDetails: Object,
  },
  items: [
    {
      productId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Product",
      },
      name: String,
      price: Number,
      quantity: {
        type: Number,
        min: 1,
        default: 1,
      },
    },
  ],
  subtotal: {
    type: Number,
    required: true,
    min: 0,
  },
  deliveryFee: {
    type: Number,
    default: 28,
  },
  tax: {
    type: Number,
    default: 0,
    min: 0,
  },
  discount: {
    type: Number,
    default: 0,
  },
  coinDiscount: {
    type: Number,
    default: 0,
  },
  coinsRedeemed: {
    type: Number,
    default: 0,
  },
  couponCode: String,
  totalAmount: {
    type: Number,
    required: true,
    min: 0,
  },
  paymentMethod: {
    type: String,
    enum: ["COD", "RAZORPAY"],
    default: "COD",
  },
  paymentStatus: {
    type: String,
    enum: ["PENDING", "PAID", "FAILED", "REFUNDED", "NA"],
    default: "NA", // NA = COD (no online payment)
  },
  // Razorpay specific fields
  razorpayOrderId: {
    type: String,
  },
  razorpayPaymentId: {
    type: String,
  },
  razorpayEmail: {
    type: String,
  },
  razorpayPhone: {
    type: String,
  },
  razorpayMethod: {
    type: String,
  },
  razorpayVPA: {
    type: String,
  },
  razorpayCardDetails: {
    type: String,
  },
  status: {
    type: String,
    enum: [
      "CREATED",
      "ACCEPTED_BY_ADMIN",
      "ASSIGNED_TO_DELIVERY",
      "PICKED_UP",
      "OUT_FOR_DELIVERY",
      "ARRIVED_AT_LOCATION",
      "OTP_VERIFIED",
      "DELIVERED",
      "CANCELLED",
    ],
    default: "CREATED",
  },
  deliveryPartnerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  deliveryOTP: {
    code: String,
    generatedAt: Date,
    verifiedAt: Date,
  },
  estimatedDeliveryTime: Date,
  actualDeliveryTime: Date,
  paymentLockUntil: {
    type: Date,
  },
  paymentInitiatedAt: {
    type: Date,
  },
  paymentCompletedAt: {
    type: Date,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Generate order ID before saving
orderSchema.pre("save", function (next) {
  if (!this.orderId) {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let result = "";

    for (let i = 0; i < 6; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }

    this.orderId = `ORD-${result}`;
  }
  next();
});

// Indexes
orderSchema.index({ userId: 1 });
orderSchema.index({ razorpayOrderId: 1 });
orderSchema.index({ paymentStatus: 1 });
orderSchema.index({ status: 1 });
orderSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model("Order", orderSchema);
