const mongoose = require("mongoose");

const orderSchema = new mongoose.Schema({
  orderId: {
    type: String,
    unique: true,
    // Not required - will be auto-generated by pre-save hook
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  deliveryAddress: {
    addressId: mongoose.Schema.Types.ObjectId,
    addressDetails: Object,
  },
  items: [
    {
      productId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Product",
      },
      name: String,
      price: Number,
      quantity: {
        type: Number,
        min: 1,
        default: 1,
      },
    },
  ],
  subtotal: {
    type: Number,
    required: true,
    min: 0,
  },
  deliveryFee: {
    type: Number,
    default: 30,
  },
  discount: {
    type: Number,
    default: 0,
  },
  couponCode: String,
  totalAmount: {
    type: Number,
    required: true,
    min: 0,
  },
  paymentMethod: {
    type: String,
    enum: ["COD"],
    default: "COD",
  },
  status: {
    type: String,
    enum: [
      "CREATED",
      "ACCEPTED_BY_ADMIN",
      "ASSIGNED_TO_DELIVERY",
      "PICKED_UP",
      "OUT_FOR_DELIVERY",
      "ARRIVED_AT_LOCATION",
      "OTP_VERIFIED",
      "DELIVERED",
      "CANCELLED",
    ],
    default: "CREATED",
  },
  deliveryPartnerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  deliveryOTP: {
    code: String,
    generatedAt: Date,
    verifiedAt: Date,
  },
  estimatedDeliveryTime: Date,
  actualDeliveryTime: Date,
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Generate order ID before saving
orderSchema.pre("save", function (next) {
  if (!this.orderId) {
    const date = new Date();
    const timestamp = date.getTime();
    this.orderId = `ORD-${timestamp}-${Math.floor(Math.random() * 1000)}`;
  }
  next();
});

module.exports = mongoose.model("Order", orderSchema);
